/*
 * Copyright (c) 2023 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include <stdio.h>
#include <stddef.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/sensor.h>
#include <zephyr/drivers/sensor/npm13xx_charger.h>
#include <zephyr/drivers/regulator.h>
#include <zephyr/fs/fs.h>
#include <zephyr/fs/littlefs.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/shell/shell.h>
#include <zephyr/storage/flash_map.h>
#include <zephyr/sys/crc.h>
#include <nrf_fuel_gauge.h>

#include "oled.h"
#include "pmic.h"

LOG_MODULE_REGISTER(pmic, LOG_LEVEL_INF);

/* PMIC devices */
static const struct device *charger_dev = DEVICE_DT_GET(DT_NODELABEL(npm1300_charger));
static const struct device *pmic_gpio_dev = DEVICE_DT_GET(DT_NODELABEL(npm1300_gpio));
static const struct device *pmic_regulators = DEVICE_DT_GET(DT_NODELABEL(npm1300_regulators));

/* Charger status bitmasks (BCHGCHARGESTATUS register) */
#define CHG_STATUS_COMPLETE_MASK BIT(1)
#define CHG_STATUS_TRICKLE_MASK  BIT(2)
#define CHG_STATUS_CC_MASK       BIT(3)
#define CHG_STATUS_CV_MASK       BIT(4)
#define CHG_STATUS_ACTIVE_MASK   (CHG_STATUS_TRICKLE_MASK | CHG_STATUS_CC_MASK | \
					  CHG_STATUS_CV_MASK)

/* UI smoothing keeps a transient voltage/current correction from making the
 * OLED jump. The nRF Fuel Gauge remains the source of truth; this only affects
 * the rounded percentage that is shown to the operator. */
#define SOC_SMOOTH_ALPHA  0.15f
#define SOC_MAX_DELTA     1.0f

/* Fuel-gauge state persistence. The envelope makes state from a different
 * battery model or library-state layout invalid automatically. */
#define FG_STATE_KEY             "battery/fg_state"
#define FG_STATE_MAGIC           0x46475331U /* "FGS1" */
#define FG_STATE_FORMAT_VERSION  1U
#define FG_STATE_BUF_SIZE        512U

struct fg_state_record {
	uint32_t magic;
	uint16_t format_version;
	uint16_t state_size;
	uint32_t model_crc;
	uint8_t state[FG_STATE_BUF_SIZE];
};

/* Keep the test firmware on the exact same model as the application. */
static const struct battery_model battery_model = {
#include "../../../applications/clip/src/battery_model.inc"
};

FS_LITTLEFS_DECLARE_DEFAULT_CONFIG(lfs_storage_cfg);
static struct fs_mount_t lfs_mnt = {
	.type = FS_LITTLEFS,
	.fs_data = &lfs_storage_cfg,
	.mnt_point = "/lfs",
	.storage_dev = (void *)FIXED_PARTITION_ID(lfs_partition),
};

static struct fg_state_record fg_state_record;
static bool fg_state_loaded;
static bool fg_settings_ready;
static bool fg_initialized;
static int64_t fg_ref_time;
static int32_t chg_status_prev;
static uint8_t last_display_percent = 255U;
static uint8_t last_saved_percent = 255U;
static float smoothed_soc;
static bool soc_initialized;
static struct {
	uint32_t voltage_mv;
	uint8_t percent;
	bool charging;
	int32_t temp_c;
	bool valid;
} last_battery_display;
static bool battery_display_error_reported;
static bool battery_display_rendered;
static K_MUTEX_DEFINE(pmic_mutex);
static struct k_work_delayable battery_display_work;

/* Voltage fallback if the fuel-gauge library cannot initialize. It is only a
 * fallback; regular operation uses the model + voltage + current + NTC data. */
struct volt_soc_entry {
	uint32_t mv;
	uint8_t soc;
};

static const struct volt_soc_entry volt_soc_table[] = {
	{4150, 100}, {4060, 90}, {3980, 80}, {3900, 70}, {3820, 60},
	{3740, 50}, {3660, 40}, {3570, 30}, {3480, 20}, {3390, 10},
	{3300, 0},
};

static uint8_t voltage_to_soc(uint32_t mv)
{
	if (mv >= volt_soc_table[0].mv) {
		return 100;
	}
	if (mv <= volt_soc_table[ARRAY_SIZE(volt_soc_table) - 1].mv) {
		return 0;
	}

	for (size_t i = 0; i < ARRAY_SIZE(volt_soc_table) - 1; i++) {
		const struct volt_soc_entry *hi = &volt_soc_table[i];
		const struct volt_soc_entry *lo = &volt_soc_table[i + 1];

		if (mv <= hi->mv && mv > lo->mv) {
			return lo->soc + (uint8_t)((mv - lo->mv) * (hi->soc - lo->soc) /
						     (hi->mv - lo->mv));
		}
	}

	return 0;
}

static uint32_t fg_model_crc(void)
{
	return crc32_ieee((const uint8_t *)&battery_model, sizeof(battery_model));
}

static void fg_state_reset(void)
{
	memset(&fg_state_record, 0, sizeof(fg_state_record));
	fg_state_loaded = false;
}

static int fg_state_settings_set(const char *key, size_t len,
				 settings_read_cb read_cb, void *cb_arg)
{
	ARG_UNUSED(key);
	const size_t expected_len = offsetof(struct fg_state_record, state) +
				    nrf_fuel_gauge_state_size;

	/* The legacy raw blob intentionally does not pass this check. Restoring a
	 * state generated by another model risks an immediate, incorrect SoC jump. */
	if (len != expected_len) {
		LOG_WRN("Ignoring incompatible fuel-gauge state (size %u)",
			(unsigned int)len);
		fg_state_reset();
		return 0;
	}

	fg_state_reset();
	ssize_t n = read_cb(cb_arg, &fg_state_record, len);
	if (n != (ssize_t)len || fg_state_record.magic != FG_STATE_MAGIC ||
	    fg_state_record.format_version != FG_STATE_FORMAT_VERSION ||
	    fg_state_record.state_size != nrf_fuel_gauge_state_size ||
	    fg_state_record.model_crc != fg_model_crc()) {
		LOG_WRN("Ignoring fuel-gauge state from a different model/version");
		fg_state_reset();
		return 0;
	}

	fg_state_loaded = true;
	return 0;
}
SETTINGS_STATIC_HANDLER_DEFINE(fg_state, "battery/fg_state", NULL,
			      fg_state_settings_set, NULL, NULL);

static int fg_storage_init(void)
{
	int ret = fs_mount(&lfs_mnt);
	if (ret != 0 && ret != -EBUSY) {
		LOG_WRN("LittleFS mount failed: %d; SoC state will not persist", ret);
		return ret;
	}

	ret = settings_subsys_init();
	if (ret != 0) {
		LOG_WRN("Settings init failed: %d; SoC state will not persist", ret);
		return ret;
	}

	fg_state_reset();
	ret = settings_load_subtree("battery");
	if (ret != 0) {
		LOG_WRN("Fuel-gauge state load failed: %d", ret);
		return ret;
	}

	fg_settings_ready = true;
	return 0;
}

/* Caller holds pmic_mutex. */
static int fg_state_save_locked(void)
{
	const size_t save_len = offsetof(struct fg_state_record, state) +
				nrf_fuel_gauge_state_size;

	if (!fg_initialized || !fg_settings_ready) {
		return -EAGAIN;
	}
	if (nrf_fuel_gauge_state_size > sizeof(fg_state_record.state)) {
		LOG_ERR("Fuel-gauge state is too large (%u > %u)",
			(unsigned int)nrf_fuel_gauge_state_size,
			(unsigned int)sizeof(fg_state_record.state));
		return -EFBIG;
	}

	fg_state_record.magic = FG_STATE_MAGIC;
	fg_state_record.format_version = FG_STATE_FORMAT_VERSION;
	fg_state_record.state_size = nrf_fuel_gauge_state_size;
	fg_state_record.model_crc = fg_model_crc();

	int ret = nrf_fuel_gauge_state_get(fg_state_record.state,
					   sizeof(fg_state_record.state));
	if (ret != 0) {
		LOG_WRN("Fuel-gauge state get failed: %d", ret);
		return ret;
	}

	ret = settings_save_one(FG_STATE_KEY, &fg_state_record, save_len);
	if (ret == 0) {
		fg_state_loaded = true;
	}
	return ret;
}

int pmic_battery_state_save(void)
{
	int ret;

	k_mutex_lock(&pmic_mutex, K_FOREVER);
	ret = fg_state_save_locked();
	k_mutex_unlock(&pmic_mutex);

	if (ret != 0 && ret != -EAGAIN) {
		LOG_WRN("Fuel-gauge state save failed: %d", ret);
	}
	return ret;
}

static int read_sensors(float *voltage, float *current, float *temp, int32_t *chg_status)
{
	struct sensor_value val;
	int ret = sensor_sample_fetch(charger_dev);
	if (ret < 0) {
		return ret;
	}

	ret = sensor_channel_get(charger_dev, SENSOR_CHAN_GAUGE_VOLTAGE, &val);
	if (ret < 0) {
		return ret;
	}
	*voltage = (float)val.val1 + ((float)val.val2 / 1000000.0f);

	ret = sensor_channel_get(charger_dev, SENSOR_CHAN_GAUGE_TEMP, &val);
	if (ret == 0) {
		*temp = (float)val.val1 + ((float)val.val2 / 1000000.0f);
	} else {
		/* Voltage is sufficient to keep the test display useful. A missing
		 * NTC channel must not turn the OLED blank. */
		*temp = last_battery_display.valid ? (float)last_battery_display.temp_c : 25.0f;
	}

	ret = sensor_channel_get(charger_dev, SENSOR_CHAN_GAUGE_AVG_CURRENT, &val);
	if (ret == 0) {
		*current = (float)val.val1 + ((float)val.val2 / 1000000.0f);
	} else {
		*current = 0.0f;
	}

	ret = sensor_channel_get(charger_dev, SENSOR_CHAN_NPM13XX_CHARGER_STATUS, &val);
	if (ret == 0) {
		*chg_status = val.val1;
	} else {
		*chg_status = 0;
	}

	return 0;
}

static bool poll_vbus_status(void)
{
	struct sensor_value val;

	return sensor_channel_get(charger_dev, SENSOR_CHAN_NPM13XX_CHARGER_VBUS_STATUS,
				  &val) == 0 && val.val1 != 0;
}

static int charge_status_inform(int32_t chg_status)
{
	union nrf_fuel_gauge_ext_state_info_data state_info;

	if (chg_status & CHG_STATUS_COMPLETE_MASK) {
		state_info.charge_state = NRF_FUEL_GAUGE_CHARGE_STATE_COMPLETE;
	} else if (chg_status & CHG_STATUS_TRICKLE_MASK) {
		state_info.charge_state = NRF_FUEL_GAUGE_CHARGE_STATE_TRICKLE;
	} else if (chg_status & CHG_STATUS_CC_MASK) {
		state_info.charge_state = NRF_FUEL_GAUGE_CHARGE_STATE_CC;
	} else if (chg_status & CHG_STATUS_CV_MASK) {
		state_info.charge_state = NRF_FUEL_GAUGE_CHARGE_STATE_CV;
	} else {
		state_info.charge_state = NRF_FUEL_GAUGE_CHARGE_STATE_IDLE;
	}

	return nrf_fuel_gauge_ext_state_update(NRF_FUEL_GAUGE_EXT_STATE_INFO_CHARGE_STATE_CHANGE,
					       &state_info);
}

/* Caller holds pmic_mutex. */
static int pmic_get_battery_status_locked(uint32_t *voltage_mv, uint8_t *percent,
					  bool *charging, int32_t *temp_c)
{
	float voltage;
	float current;
	float temp;
	float raw_soc;
	int32_t chg_status;
	int ret;

	if (!device_is_ready(charger_dev)) {
		return -ENODEV;
	}

	ret = read_sensors(&voltage, &current, &temp, &chg_status);
	if (ret < 0) {
		LOG_WRN("Battery sensor read failed: %d", ret);
		return ret;
	}

	*voltage_mv = (uint32_t)(voltage * 1000.0f);
	*temp_c = (int32_t)temp;
	*charging = (chg_status & CHG_STATUS_ACTIVE_MASK) != 0;

	if (fg_initialized) {
		bool vbus_connected = poll_vbus_status();
		ret = nrf_fuel_gauge_ext_state_update(
			vbus_connected ? NRF_FUEL_GAUGE_EXT_STATE_INFO_VBUS_CONNECTED
				       : NRF_FUEL_GAUGE_EXT_STATE_INFO_VBUS_DISCONNECTED,
			NULL);
		if (ret < 0) {
			LOG_WRN("Fuel-gauge VBUS update failed: %d", ret);
		}

		if (chg_status != chg_status_prev) {
			chg_status_prev = chg_status;
			ret = charge_status_inform(chg_status);
			if (ret < 0) {
				LOG_WRN("Fuel-gauge charge-state update failed: %d", ret);
			}
		}

		/* The NPM1300 sensor reports negative while discharging; nRF Fuel
		 * Gauge expects negative while charging, matching Nordic's sample. */
		float delta = (float)k_uptime_delta(&fg_ref_time) / 1000.0f;
		raw_soc = nrf_fuel_gauge_process(voltage, -current, temp, delta, NULL);
	} else {
		raw_soc = (float)voltage_to_soc(*voltage_mv);
	}

	if (raw_soc < 0.0f) {
		raw_soc = 0.0f;
	} else if (raw_soc > 100.0f) {
		raw_soc = 100.0f;
	}

	if (!soc_initialized || raw_soc < 10.0f) {
		smoothed_soc = raw_soc;
		soc_initialized = true;
	} else {
		float delta = raw_soc - smoothed_soc;
		if (delta > SOC_MAX_DELTA) {
			delta = SOC_MAX_DELTA;
		} else if (delta < -SOC_MAX_DELTA) {
			delta = -SOC_MAX_DELTA;
		}
		smoothed_soc += SOC_SMOOTH_ALPHA * delta;
	}

	uint8_t display_percent = (uint8_t)(smoothed_soc + 0.5f);
	/* Make the displayed percentage monotonic inside a phase. This prevents a
	 * relaxed cell voltage or rounding from showing 78 -> 79 while discharging
	 * or 79 -> 78 while charging. */
	if (last_display_percent != 255U &&
	    ((*charging && display_percent < last_display_percent) ||
	     (!*charging && display_percent > last_display_percent))) {
		LOG_DBG("Holding battery at %u%% while %s (estimate %u%%)",
			last_display_percent, *charging ? "charging" : "discharging",
			display_percent);
		display_percent = last_display_percent;
	}

	last_display_percent = display_percent;
	*percent = display_percent;
	last_battery_display.voltage_mv = *voltage_mv;
	last_battery_display.percent = display_percent;
	last_battery_display.charging = *charging;
	last_battery_display.temp_c = *temp_c;
	last_battery_display.valid = true;

	/* Write only once per displayed percentage (and once after boot). */
	if (fg_initialized && display_percent != last_saved_percent) {
		ret = fg_state_save_locked();
		if (ret == 0) {
			last_saved_percent = display_percent;
		} else if (ret != -EAGAIN) {
			LOG_WRN("Fuel-gauge state save failed: %d", ret);
		}
	}

	return 0;
}

int pmic_get_battery_status(uint32_t *voltage_mv, uint8_t *percent, bool *charging,
			    int32_t *temp_c)
{
	int ret;

	k_mutex_lock(&pmic_mutex, K_FOREVER);
	ret = pmic_get_battery_status_locked(voltage_mv, percent, charging, temp_c);
	k_mutex_unlock(&pmic_mutex);

	return ret;
}

static void battery_display_handler(struct k_work *work)
{
	ARG_UNUSED(work);

	uint32_t voltage_mv;
	uint8_t percent;
	bool charging;
	int32_t temp_c;

	int ret = pmic_get_battery_status(&voltage_mv, &percent, &charging, &temp_c);
	if (ret == 0) {
		oled_show_battery(percent, voltage_mv, charging, temp_c);
		if (!battery_display_rendered) {
			LOG_INF("OLED battery screen: %u%%, %u mV", percent, voltage_mv);
			battery_display_rendered = true;
		}
		battery_display_error_reported = false;
	} else {
		if (!battery_display_error_reported) {
			LOG_WRN("Battery display using fallback: %d", ret);
			battery_display_error_reported = true;
		}

		k_mutex_lock(&pmic_mutex, K_FOREVER);
		bool have_cached_status = last_battery_display.valid;
		voltage_mv = last_battery_display.voltage_mv;
		percent = last_battery_display.percent;
		charging = last_battery_display.charging;
		temp_c = last_battery_display.temp_c;
		k_mutex_unlock(&pmic_mutex);

		if (have_cached_status) {
			oled_show_battery(percent, voltage_mv, charging, temp_c);
		} else {
			oled_show_battery_unavailable();
		}
	}

	k_work_schedule(&battery_display_work, K_SECONDS(1));
}

int pmic_init(void)
{
	int ret = 0;

	LOG_INF("Initializing PMIC (NPM1300)...");

	if (!device_is_ready(charger_dev)) {
		LOG_WRN("npm1300 charger not ready");
		ret = -ENODEV;
	} else {
		LOG_INF("  npm1300_charger: ready");
	}
	if (!device_is_ready(pmic_gpio_dev)) {
		LOG_WRN("npm1300_gpio not ready");
		ret = -ENODEV;
	} else {
		LOG_INF("  npm1300_gpio: ready (5 GPIOs available)");
	}
	if (!device_is_ready(pmic_regulators)) {
		LOG_WRN("npm1300 regulators not ready");
		ret = -ENODEV;
	} else {
		LOG_INF("  npm1300_regulators: ready");
	}
	if (ret != 0) {
		k_work_init_delayable(&battery_display_work, battery_display_handler);
		k_work_schedule(&battery_display_work, K_NO_WAIT);
		return ret;
	}

	(void)fg_storage_init(); /* Continue with a non-persistent gauge on failure. */

	float voltage;
	float current;
	float temp;
	int32_t chg_status;
	ret = read_sensors(&voltage, &current, &temp, &chg_status);
	if (ret < 0) {
		LOG_WRN("Fuel-gauge init sensor read failed: %d", ret);
	} else {
		struct nrf_fuel_gauge_init_parameters init_params = {
			.v0 = voltage,
			.i0 = -current,
			.t0 = temp,
			.model = &battery_model,
			.opt_params = NULL,
			.state = fg_state_loaded ? fg_state_record.state : NULL,
		};

		ret = nrf_fuel_gauge_init(&init_params, NULL);
		if (ret < 0) {
			LOG_WRN("Fuel-gauge init failed: %d; using voltage fallback", ret);
		} else {
			struct sensor_value value;
			fg_initialized = true;
			fg_ref_time = k_uptime_get();
			chg_status_prev = chg_status;

			LOG_INF("Fuel gauge %s (%s state)", nrf_fuel_gauge_version,
				fg_state_loaded ? "restored" : "new");
			(void)charge_status_inform(chg_status);
			(void)nrf_fuel_gauge_ext_state_update(
				poll_vbus_status() ? NRF_FUEL_GAUGE_EXT_STATE_INFO_VBUS_CONNECTED
						   : NRF_FUEL_GAUGE_EXT_STATE_INFO_VBUS_DISCONNECTED,
				NULL);

			if (sensor_channel_get(charger_dev,
					       SENSOR_CHAN_GAUGE_DESIRED_CHARGING_CURRENT,
					       &value) == 0) {
				float max_current = (float)value.val1 +
					((float)value.val2 / 1000000.0f);
				(void)nrf_fuel_gauge_ext_state_update(
					NRF_FUEL_GAUGE_EXT_STATE_INFO_CHARGE_CURRENT_LIMIT,
					&(union nrf_fuel_gauge_ext_state_info_data){
						.charge_current_limit = max_current,
					});
				(void)nrf_fuel_gauge_ext_state_update(
					NRF_FUEL_GAUGE_EXT_STATE_INFO_TERM_CURRENT,
					&(union nrf_fuel_gauge_ext_state_info_data){
						.charge_term_current = max_current / 10.0f,
					});
			}
		}
	}

	/* PMIC init follows OLED init in main(), so the status display is live for
	 * the entire hardware-test session. */
	k_work_init_delayable(&battery_display_work, battery_display_handler);
	k_work_schedule(&battery_display_work, K_NO_WAIT);

	return 0;
}

/* Enable/disable charging at runtime.
 * Uses desired-charging-current: 0 clears the charger enable bit, non-zero
 * sets it and makes the PMIC use the DTS-programmed current. */
#define CHARGE_CURRENT_MA 220

int pmic_charger_set(bool enable)
{
	struct sensor_value val = {
		.val1 = enable ? CHARGE_CURRENT_MA : 0,
		.val2 = 0,
	};

	if (!device_is_ready(charger_dev)) {
		return -ENODEV;
	}

	int ret = sensor_attr_set(charger_dev,
				  SENSOR_CHAN_GAUGE_DESIRED_CHARGING_CURRENT,
				  SENSOR_ATTR_CONFIGURATION, &val);
	if (ret != 0) {
		LOG_ERR("pmic_charger_set(%d) failed: %d", enable, ret);
	}
	return ret;
}

static int pmic_enter_ship_mode(void)
{
	struct k_work_sync sync;

	if (!device_is_ready(pmic_regulators)) {
		return -ENODEV;
	}

	/* Stop the 1 s battery/OLED refresh so it stops reading the dying fuel
	 * gauge ("Battery sensor read failed: -5" spam) and stops writing garbage
	 * to the OLED as I2C2 loses power. Mirrors the app's clean power-off
	 * (applications/clip clip_event.c POWER_OFF_EXEC). */
	(void)k_work_cancel_delayable_sync(&battery_display_work, &sync);
	oled_test_clear();

	(void)pmic_battery_state_save();
	LOG_INF("Entering ship mode (power off)...");
	k_sleep(K_MSEC(100));
	return regulator_parent_ship_mode(pmic_regulators);
}

static int pmic_get_charger_status_string(char *buf, size_t len)
{
	struct sensor_value val;
	int ret;

	ret = sensor_sample_fetch(charger_dev);
	if (ret < 0) {
		snprintk(buf, len, "Sample fetch failed: %d", ret);
		return ret;
	}
	ret = sensor_channel_get(charger_dev, SENSOR_CHAN_NPM13XX_CHARGER_STATUS, &val);
	if (ret < 0) {
		snprintk(buf, len, "Read failed: %d", ret);
		return ret;
	}

	const char *state = (val.val1 & CHG_STATUS_COMPLETE_MASK) ? "Complete" :
		(val.val1 & CHG_STATUS_CV_MASK) ? "CV" :
		(val.val1 & CHG_STATUS_CC_MASK) ? "CC" :
		(val.val1 & CHG_STATUS_TRICKLE_MASK) ? "Trickle" : "Not charging";
	snprintk(buf, len, "%s (0x%02x)", state, (unsigned int)val.val1);
	return 0;
}

static int cmd_pmic_status(const struct shell *sh, size_t argc, char **argv)
{
	ARG_UNUSED(argc);
	ARG_UNUSED(argv);

	uint32_t voltage_mv;
	uint8_t percent;
	bool charging;
	int32_t temp_c;
	char status[32];
	int ret = pmic_get_battery_status(&voltage_mv, &percent, &charging, &temp_c);

	if (ret == 0) {
		(void)pmic_get_charger_status_string(status, sizeof(status));
		shell_print(sh, "Battery: %u%%, %u mV, %dC, %s", percent, voltage_mv,
			    temp_c, charging ? "charging" : "discharging");
		shell_print(sh, "Charger: %s", status);
	} else {
		shell_error(sh, "Battery read failed: %d", ret);
	}

	return ret;
}

static int cmd_pmic_monitor(const struct shell *sh, size_t argc, char **argv)
{
	int max_iter = 10;

	if (argc >= 2) {
		max_iter = strtol(argv[1], NULL, 10);
		if (max_iter <= 0) {
			return -EINVAL;
		}
	}

	for (int i = 0; i < max_iter; i++) {
		uint32_t voltage_mv;
		uint8_t percent;
		bool charging;
		int32_t temp_c;

		if (pmic_get_battery_status(&voltage_mv, &percent, &charging, &temp_c) == 0) {
			shell_print(sh, "[%d] %u%% | %u mV | %dC | %s", i + 1, percent,
				    voltage_mv, temp_c, charging ? "Charging" : "Discharging");
		}
		k_sleep(K_SECONDS(1));
	}

	return 0;
}

static int cmd_pmic_ship(const struct shell *sh, size_t argc, char **argv)
{
	ARG_UNUSED(argc);
	ARG_UNUSED(argv);

	shell_print(sh, "Saving battery state and entering ship mode...");
	return pmic_enter_ship_mode();
}

SHELL_STATIC_SUBCMD_SET_CREATE(sub_pmic,
	SHELL_CMD(status, NULL, "Show filtered battery and charger status", cmd_pmic_status),
	SHELL_CMD_ARG(monitor, NULL, "Monitor battery status [iterations]", cmd_pmic_monitor, 0, 1),
	SHELL_CMD(ship, NULL, "Save battery state and enter ship mode", cmd_pmic_ship),
	SHELL_SUBCMD_SET_END
);

SHELL_CMD_REGISTER(pmic, &sub_pmic, "PMIC (NPM1300) commands", NULL);
